### ISSUE TITLE
Cannot build example because of incorrect schema location

### ISSUE THREAD

**Issue by uliSchuster** [claudemamo/smooks-java-to-edifact#1]
When In clone this example and do a `mvn clean install`,  the build fails with the following error:
```
org.xml.sax.SAXParseException; systemId: file:<some-path>/smooks-java-to-edifact/target/generated-resources/EDIFACT-Common/EDIFACT-Service-Segments-4.1.dfdl.xsd; lineNumber: 40; columnNumber: 75; schema_reference.4: Failed to read schema document '/EDIFACT-Common/IBM_EDI_Format.dfdl.xsd'
```
... plus some more similar errors. The root cause seems to be that the reference to `IBM_EDI_Format.dfdl.xsd` is referenced via an absolute path, like:
```
 <xsd:import namespace="http://www.ibm.com/dfdl/EDI/Format"
             schemaLocation="/EDIFACT-Common/IBM_EDI_Format.dfdl.xsd"/>
```
Is there a way to change these references in all affected schema files? Manually editing the downloaded schemas doesn't appear to be the proper portable way to handle this issue.

**Comment by cjmamo** [comment]
This example is outdated. The official example is at https://github.com/smooks/smooks-examples/tree/v1.0.2/java-to-edifact.
